### ISSUE TITLE
Various potential improvements.

### ISSUE THREAD

**Issue by tedthepraimortis** [DizzyLove/HD-Dizzy-Addon#1]
## Archival Files

Stuff like the various .pk3s and .wads could likely be kept as their own separate mod or included as somewhat modified versions in it rather than an archive to allow potential editing.

## ZScript Overrides

This is the main thing, other than newrange, that'd cause multiplayer desyncs, plus I'd prefer if it's not included in this and instead just kept in Ted-Tweaks. The DESPMASK Graphic will work for it either way.

## README.md issues

Markdownlint has a couple suggested rules, most notably doing stuff like using a lot of titles, that being singular hash, especially for stuff like lists where you can use an asterisk or dash instead. I'd suggest also doing credits in a list too to make it a bit more noticeable that they're credits rather than a title along with having another list for notable changes, like I do in **[Radtech Weapons Pack](https://github.com/swampyrad/RadTechWeaponsPack/blob/main/README.md)**

Here's also a whole guide on Markdownlint and it's general rules: https://github.com/DavidAnson/markdownlint/blob/v0.26.2/doc/Rules.md

**Comment by DizzyLove** [comment]
Kinda made it tidier I think. I hope.😔
